language: node_js
node_js:
  - '6'
  - '8'

notifications:
  email: false
  # webhooks:
  #   urls:
  #     - https://webhooks.gitter.im/e/...
  #   on_success: change  # options: [always|never|change] default: always
  #   on_failure: always  # options: [always|never|change] default: always
  #   on_start: never     # options: [always|never|change] default: always

script:
  - npm run dist

after_success:

deploy:
  provider: npm
  email: patricksissons@gmail.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: "UELXyFP1Sx+lHKLCpL55E9dOEmShPm0HMcF4uCp7kaZeXG29Q7P3WEY+sDuhDNz4/tQs3i74wH5wba7mY42a9AwVPr2mANB4QncSNPhDFC+CMrfD4+tcSIBxm6p9Wl0GtFxudB7qprFsu+Rvo/RySFu37LSbA/9C4G/PnIN/cbpJBhmS0sU7H4v9kwDPoGGAZIBAcepoqw9NipL6ooAFz1/nU3g5V0ycBR29gb6WWu3AOTLQNy9f0E/90ZVg1TYNf009fb6Ic9PZukUwko6U8DufO49vuDeeKv6zannCWiFojTnjrj8oRxE/IcMLFixG5ZRzZcbUtCKlzYRFepbIUqlLRDizh9q1XIN/8z5UuhKyWwhYSqtWLCK3pT6D3ep1LZbp+S03CpXML1xbyo5ZYb8rhjoC/RlnY/qnyhWLf+P/5AsFhd+scO0yRi5rLyCXq5nsVZMCBAJ5OCwXqa2XCrDLFkNw+vc0NUQnUVKA3F8IPOPYhRpzhf0jkB9TrqcoLJsDQvfo8olYjhzYy05sBkyz9Ccci8M7M0bVtQYMfNBQDPJnCRsowf6xmevk+zF7dtE/vhVN85V3b1qG+JHHUcp6sW+ahVfLPm3T1TeMjoIghSye7ssoCy8n9Abc/3mNLPdp6xgwK1qDy64vze8ElgaBq7vR/fyDt22XqEM0Nqg="
